# Generated by Django 2.0.2 on 2018-02-25 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', 'create_todolists'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 26, 12, 42, 7, 751946)),
        ),
    ]
