# Generated by Django 2.0.2 on 2018-02-22 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from calendar_util.constants import TIMEZONE

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=TIMEZONE)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
