# Generated by Django 2.0.2 on 2018-02-25 14:40

from django.db import migrations
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_auto_20180225_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=lists.models.DueDateField(),
        ),
    ]
