# Generated by Django 2.0.2 on 2018-02-26 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0003_auto_20180225_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.CharField(choices=[('DLY', 'daily'), ('MTH', 'monthly'), ('QTR', 'quarterly'), ('YLY', 'yearly')], default='DLY', max_length=3)),
                ('offset', models.IntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.TodoList')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
