# Generated by Django 2.0.2 on 2018-02-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
