# Generated by Django 2.0.2 on 2018-02-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_schedule_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='from_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.Schedule'),
        ),
    ]
