# Generated by Django 2.0.2 on 2018-02-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_todo_from_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('due_date',)},
        ),
    ]
